language: node_js
node_js:
- node
install:
- yarn install
- yarn global add codecov
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pascal@slamcode.com
  api_key:
    secure: XdM3WYCT+RcRzwfFbW5rzIIOjTX8ztn/eOeoeSBqIV+n+/C5KJWK6SNdmSAaz2qggCifzItQkIcDo5AUvwpbAr94aoKDakLumgkkM2gSStqetWORBIJmLwxdEp9eUjYfv6sTVH3Sv11gtmpGdPnfdL5/XfjLdYO+38TceDO1njyeWLIYsXltFVk212hnqyaqpllFiy0LGtYY3GNqnC0pzU94bJjV8wWlO95W5OTSlFM2n0QWRLiSsJMeAk6nLoTpWpCC387spbSXVCaGJl7GcN7M2VHNOD3m8tPnvKjgucMRgUIPz8wsotQYcIBe0brcEj4h1S2ur2Wxw11TR1sbr/52JP0D0p7XTwM4fSF3cKC4DDVtuoHeeQxIeYaP35g6AmRSjXkk09gZLo/d73JAw1hQ1nVK9/4Xnp6Vpi3IZihqy5ilFB5t03We0xemL5ESpFoxJi6tgL9wK8uV4fowf+cYwsyPGSTQKqh/iOGtTfz2wbKtXZMzGmgKwqgOTaEJdB5FNAklh3C9kVuyyBKJ6rZqsNCrtQDo0NruUtBFDjWTFkOhU7nSL+krFxVmHh30H7/VwF1GzeitoX2NYFoyQM9F/5eS9TuDmtrUAoYERDhxAeY12uXFAozxfywZlXRGv1jqwiIRUImM4bAtY3cfj4JN8EsuW6qHSEvt1WprW4E=
  on:
    tags: true
    repo: herrfugbaum/qsv
after_success:
- codecov
env:
  global:
    secure: up/7oteiBBK8VkRyRXIfa9RMwRAVs0QQYWh+Mdf6KKXgEWgmp3IJdnLS4+MJ+yR2EAbWYyTfdil8/Cr249+SaD70keMClIt9bNRsdkztH1E++dgws6dLWLAX8N2376TKYKgzJmanhHOJACGJKKiiJM0asBAnvNhN7vVqJWlF6t5awWtt8+DvDI54kpS725Qc1qaFYdpI9flRZUOEmtpyEwwlbVPK2sXIG4X5GHNOQplaE9SfhjYRJRpmLS6oVtW7Y5Tlzma6xzFiRNP0HHuhqDp3LtiiZ569U9ecungOfgPBGAGrqahLqrnFd/AKJbG1eq4oIWsZ8fVXedlwBmYfEmv7U3BBIEd3EffwFh01VxID5frzPee4loTYXzBqUqhSjsBZVPcrnawHWm/4gQ15Q6vEhFyd0ucflrb5Zhrjv4Ep5bAeFnhdmtuihibgWwFycjdS+OFt9NBtKMiaAdGwKK901AGKJCi2KU3qRVLlaLUX7981DxttmnWaqtbqDhh/oew4fXdg9m7KGaa7Z+AmCZnplxJLs185savueRj9RDznXXhWKpqs5avndsQH2IANNm9MoP2X4I2oDa/gPU8e5PMPET0Q5SKuI4h+g1DzB69Shfv5haPCpGm0l2c6sIV8eKO04Xq0hg4pL+fuZNv4guJnFwUnjL+s5Y0Zx1Fmjzs=
